### PR TITLE
Batch runs

### PR DESCRIPTION
**Pull request by jamilgafur**
min_results = best particle cost per iteration
max_results = worst particle cost per iteration
ave = average cost per iteration 
std = np.std of min_results per iteration

I think this is a good start, for logging once we agree this is good I can start doing some visualizations and working on a small comparison group for P1 and get some prelim stuff out!

### CODE REVIEW

**Comment by 14corman** [comment]
Do we want to ignore csv files? The data will be held in csv files, so if we ignore them then everyone will have to run the algorithms themselves rather than run once and be done.

Should your A and b be global? If you do distributed computing for all inputs, will the different A's an b's interfere with each other, or will global only be for that particular process and not for all processes?

**Comment by jamilgafur** [comment]
Do we want to ignore csv files?
* you are right, I was told not to save data on git years ago, but this isn't anything to big

**Comment by jamilgafur** [comment]
Should your A and b be global? 
    * I updated it so that it will be internal and easy to identify for each optimizer

**Comment by 14corman** [comment]
I agree. If we were doing something groundbreaking where we needed to keep data safe, or working with company secrets, then we would not want them in a repo. However, this is running some algorithms, and collecting all of the data could take 2+ hours to run for one person.

**Pull request merged**
